version: 2
jobs:
  build:
    docker:
      - image: node:10.16.0-alpine
    steps:
        - checkout
        - run: npm install
        - run: npm run lint
        - run: npm run check
        - run: npm run test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:0a981a8c-8233-4030-90ca-856599387bda@git.heroku.com/pokedex-ts-circleci.git master
    requires:
      - build
    filters:
      branches:
        only: master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy