version: 2
jobs:
  build:
    docker:
      - image: node:10.16.0-alpine
    steps:
        - run:
            name: Install deps
            command: npm install
  lint:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - run:
          name: Lint the project
          command: npm run lint
    requires:
          - build
  check:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - run:
          name: Check the project
          command: npm run check
    requires:
          - build
  test:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - run:
          name: Run the tests
          command: npm run test
    requires:
          - build
workflows:
  version: 2
  build-deploy:
    - build
    - lint
    - check
    - test