version: 2
jobs:
  build:
    docker:
      - image: node:10.16.0-alpine
    steps:
        - checkout
        - run: npm install
        - run: npm run lint
        - run: npm run check
        - run: npm run test

  deploy:
    docker:
      - image: node:10.16.0-alpine
    steps:
      - run:
          name: Deploy the project
    filters:
        branches:
          only: master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build